spring.application.name=rag-backend
#Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5433/rag_db
spring.datasource.username=rag_user
spring.datasource.password=rag_password
#Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#Gemini
spring.ai.google.genai.api-key=${GeminiAPIKeyRAG:${GOOGLE_API_KEY:}}
#Chat
spring.ai.google.genai.chat.model=gemini-2.5-flash
spring.ai.google.genai.chat.temperature=0.0
#Embeddings
spring.ai.google.genai.embedding.api-key=${GeminiAPIKeyRAG:${GOOGLE_API_KEY:}}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.dimensions=768
spring.ai.google.genai.embedding.text.task-type=RETRIEVAL_QUERY